### ISSUE TITLE
Fail to create output plot series

### ISSUE THREAD

**Issue by rogertrullo** [lassoan/SlicerLineProfile#2]
Hi, thanks for this extension. Could you please explain how to use it?
When I try to create a new _Outplot plot series_ it does not do anything and stay in None showing this error: _outputPlotSeries.SetName('name')
AttributeError: 'NoneType' object has no attribute 'SetName'_

Thanks!

**Comment by lassoan** [comment]
I've just tested this and it works fine on the latest stable version of Slicer (Slicer-4.10.1).

If you have issues using this extension with Slicer-4.10.1 then copy-paste your application log here (menu: Help / Report a bug).

**Comment by rogertrullo** [comment]
I confirm that it works in version 4.10.1 thanks!
for the record, the issue was in version 4.8.1
